/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agent.gui;

import agent.InterfaceAgent;
import agent.model.LOList;
import agent.model.LOM;
import agent.model.SearchLO;
import agent.utils.Utils;
import com.google.gson.Gson;
import com.sun.org.apache.xerces.internal.impl.dv.xs.DecimalDV;
import jade.core.AID;
import jade.lang.acl.ACLMessage;
import java.io.File;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author magir
 */
public class GUI extends javax.swing.JFrame {
    
    private InterfaceAgent interfaceAgent;
    private File file;
    private LOList loList;
    private Integer sendedLOId;
    
    DefaultMutableTreeNode loTreeList;
    
    DefaultTreeModel model;
    
    /**
     * Creates new form GUI
     */
    public GUI(InterfaceAgent interfaceAgent) {
        initComponents();
        
        this.interfaceAgent = interfaceAgent;
        
        sendedLOId = 0;
        
        this.loTreeList = new DefaultMutableTreeNode("OA");
        this.model = new DefaultTreeModel(loTreeList);
        this.jtLOEvaluated.setModel(model);
    }
    
    public void fillLOList(LOList loList){
        
        this.loList = loList;
        
        jlNumLOResult.setText(String.valueOf(loList.getLOList().size()));
        
        for(LOM lom : loList.getLOList()){
            jcbLOList.addItem(lom.getLoId() + " - " + lom.getTitle());
        }
        
    }
    
    public void fillTreeLO(LOM lom){
        

        DefaultMutableTreeNode lo = new DefaultMutableTreeNode(
                lom.getLoId()+ " - " + lom.getTitle());
        
        DefaultMutableTreeNode accesibilityRecommendationTreeElement = new DefaultMutableTreeNode(
                    "Accesibilidad: " + Float.valueOf(lom.getAccessibilityScore()) / 10 * 100 + " %");
        
        lo.add(accesibilityRecommendationTreeElement);
        
        //Agregar las recomendaciones hechas por el agente
        for(String recommendation : lom.getRecommendationList()){
            DefaultMutableTreeNode recommendationTreeElement = new DefaultMutableTreeNode(
                    recommendation);
            
            lo.add(recommendationTreeElement);
        }
        
        loTreeList.add(lo);
        
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jpSearchLO = new javax.swing.JPanel();
        jtfSearchString = new javax.swing.JTextField();
        jl3 = new javax.swing.JLabel();
        jl5 = new javax.swing.JLabel();
        jtfLOId = new javax.swing.JTextField();
        jbSearchLO = new javax.swing.JButton();
        jl4 = new javax.swing.JLabel();
        jlNumLOResult = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbLOList = new javax.swing.JComboBox<>();
        jbSendLO = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtLOEvaluated = new javax.swing.JTree();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpSearchLO.setBackground(new java.awt.Color(0, 153, 153));
        jpSearchLO.setBorder(new javax.swing.border.MatteBorder(null));

        jtfSearchString.setToolTipText("Cadena de búsqueda");

        jl3.setText("Cadena de búsqueda:");

        jl5.setText("Cadena de búsqueda:");

        jtfLOId.setToolTipText("Cadena de búsqueda");
        jtfLOId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jbSearchLO.setText("Buscar OA");
        jbSearchLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchLOActionPerformed(evt);
            }
        });

        jl4.setText("Resultados:");

        javax.swing.GroupLayout jpSearchLOLayout = new javax.swing.GroupLayout(jpSearchLO);
        jpSearchLO.setLayout(jpSearchLOLayout);
        jpSearchLOLayout.setHorizontalGroup(
            jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfSearchString, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfLOId))
                    .addComponent(jbSearchLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNumLOResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpSearchLOLayout.setVerticalGroup(
            jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearchString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl3))
                .addGap(18, 18, 18)
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLOId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl5))
                .addGap(18, 18, 18)
                .addComponent(jbSearchLO)
                .addGap(18, 18, 18)
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl4)
                    .addComponent(jlNumLOResult, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtfLOId.getAccessibleContext().setAccessibleDescription("Id del objeto");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jbSendLO.setText("Agregar Objeto");
        jbSendLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSendLOActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jtLOEvaluated.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jtLOEvaluated);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbLOList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSendLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbLOList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSendLO)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSearchLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSearchLO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchLOActionPerformed
        
        jcbLOList.removeAllItems();
        
        Gson gson = new Gson();

        SearchLO searchLO = new SearchLO();

        searchLO.setSearchString(jtfSearchString.getText());
        
        if(!jtfLOId.getText().trim().equals("")){
            searchLO.setSearchLOId(Integer.parseInt(jtfLOId.getText()));
        }

        String json = gson.toJson(searchLO);

        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent,
            new AID("ControllerAgent", AID.ISLOCALNAME),
            "obj;" + json + ";" + "msg;" + "search lo",
            ACLMessage.INFORM);
    }//GEN-LAST:event_jbSearchLOActionPerformed

    private void jbSendLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSendLOActionPerformed
        
        LOM lom = loList.getLOList().get(jcbLOList.getSelectedIndex());
        
        Gson gson = new Gson();
        String json = gson.toJson(lom);
        
        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent, 
                new AID("ControllerAgent", AID.ISLOCALNAME), 
                "obj;" + json + ";" + "msg;" + "selected lo", 
                ACLMessage.INFORM);
    }//GEN-LAST:event_jbSendLOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbSearchLO;
    private javax.swing.JButton jbSendLO;
    private javax.swing.JComboBox<String> jcbLOList;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jl5;
    private javax.swing.JLabel jlNumLOResult;
    private javax.swing.JPanel jpSearchLO;
    private javax.swing.JTree jtLOEvaluated;
    private javax.swing.JTextField jtfLOId;
    private javax.swing.JTextField jtfSearchString;
    // End of variables declaration//GEN-END:variables
}
